// Word bank — 100+ PTE vocabulary words
const WORD_BANK = [
{ word: "Perseverance", pos: "noun", meaning: "Continuing to try even when things are hard.", example: "Her perseverance helped her get the job." },
{ word: "Diligent", pos: "adjective", meaning: "Working carefully and with great effort.", example: "A diligent worker always finishes tasks on time." },
{ word: "Eloquent", pos: "adjective", meaning: "Expressing ideas clearly and beautifully.", example: "Her eloquent speech impressed everyone." },
{ word: "Ambiguous", pos: "adjective", meaning: "Having more than one possible meaning.", example: "The question was ambiguous, so students were confused." },
{ word: "Coherent", pos: "adjective", meaning: "Clear, logical, and well-organised.", example: "Write a coherent paragraph for PTE writing." },
{ word: "Substantial", pos: "adjective", meaning: "Large in size, value, or importance.", example: "He made a substantial improvement in his score." },
{ word: "Acknowledge", pos: "verb", meaning: "To admit or recognise something is true.", example: "She acknowledged her mistake and moved forward." },
{ word: "Proficiency", pos: "noun", meaning: "A high level of skill or ability.", example: "English proficiency is needed for PR in Australia." },
{ word: "Consequently", pos: "adverb", meaning: "As a result; therefore.", example: "He studied hard; consequently, he passed the exam." },
{ word: "Initiative", pos: "noun", meaning: "The ability to act without being told.", example: "Taking initiative at work helps your career." },
{ word: "Facilitate", pos: "verb", meaning: "To make something easier or help it happen.", example: "Good tools facilitate learning." },
{ word: "Resilience", pos: "noun", meaning: "Ability to recover quickly from difficulties.", example: "Moving to a new country requires resilience." },
{ word: "Bureaucracy", pos: "noun", meaning: "A system with many official rules and processes.", example: "Australian visa bureaucracy can be complex." },
{ word: "Vocabulary", pos: "noun", meaning: "All the words a person knows or uses.", example: "A strong vocabulary helps in PTE writing." },
{ word: "Commitment", pos: "noun", meaning: "A promise or strong dedication to something.", example: "Commitment to learning English is essential." },
{ word: "Beneficial", pos: "adjective", meaning: "Having a good or helpful effect.", example: "Exercise is beneficial for your health." },
{ word: "Emphasise", pos: "verb", meaning: "To give special importance to something.", example: "Teachers emphasise good grammar in PTE." },
{ word: "Circumstances", pos: "noun", meaning: "The conditions or facts around a situation.", example: "Under difficult circumstances, she still succeeded." },
{ word: "Adequate", pos: "adjective", meaning: "Enough; satisfactory for a purpose.", example: "You need adequate English for skilled migration." },
{ word: "Simultaneously", pos: "adverb", meaning: "At the same time.", example: "She worked and studied simultaneously." },
{ word: "Analyse", pos: "verb", meaning: "To examine something in detail.", example: "Analyse the data before making a decision." },
{ word: "Approach", pos: "noun", meaning: "A way of dealing with something.", example: "Her approach to study is very organised." },
{ word: "Assessment", pos: "noun", meaning: "An evaluation or judgement of something.", example: "The assessment showed his strengths in writing." },
{ word: "Assumption", pos: "noun", meaning: "Something accepted as true without proof.", example: "Do not make assumptions about other cultures." },
{ word: "Authority", pos: "noun", meaning: "The power to make decisions.", example: "The teacher has authority in the classroom." },
{ word: "Available", pos: "adjective", meaning: "Able to be used or obtained.", example: "Free wifi is available at the library." },
{ word: "Cautious", pos: "adjective", meaning: "Careful to avoid danger.", example: "Be cautious when crossing the road." },
{ word: "Challenge", pos: "noun", meaning: "A difficult task that tests ability.", example: "Learning English is a big challenge." },
{ word: "Collaborate", pos: "verb", meaning: "To work together with others.", example: "Students collaborate on group projects." },
{ word: "Community", pos: "noun", meaning: "A group of people living in one place.", example: "She is active in the local community." },
{ word: "Complex", pos: "adjective", meaning: "Made of many parts; complicated.", example: "Grammar rules can be complex." },
{ word: "Conclude", pos: "verb", meaning: "To bring to an end or decide.", example: "He concluded the meeting at noon." },
{ word: "Conduct", pos: "verb", meaning: "To organise and carry out.", example: "They conducted a survey on transport." },
{ word: "Considerable", pos: "adjective", meaning: "Notably large in amount.", example: "She has considerable experience in teaching." },
{ word: "Consistent", pos: "adjective", meaning: "Acting the same way over time.", example: "Consistent practice improves your score." },
{ word: "Contemporary", pos: "adjective", meaning: "Belonging to the present time.", example: "Contemporary art can be unusual." },
{ word: "Contribute", pos: "verb", meaning: "To give in order to help.", example: "Everyone contributed ideas to the project." },
{ word: "Convenient", pos: "adjective", meaning: "Easy to use or suitable.", example: "Online shopping is very convenient." },
{ word: "Crucial", pos: "adjective", meaning: "Extremely important.", example: "Sleep is crucial for good health." },
{ word: "Currency", pos: "noun", meaning: "Money used in a country.", example: "The currency in Japan is the yen." },
{ word: "Deliberate", pos: "adjective", meaning: "Done on purpose.", example: "It was a deliberate decision to move." },
{ word: "Demonstrate", pos: "verb", meaning: "To show clearly.", example: "Please demonstrate how this works." },
{ word: "Diversity", pos: "noun", meaning: "A range of different things or people.", example: "Australia is known for cultural diversity." },
{ word: "Economic", pos: "adjective", meaning: "Relating to economy or money matters.", example: "Economic growth helps employment." },
{ word: "Efficient", pos: "adjective", meaning: "Working well without waste.", example: "Electric cars are very efficient." },
{ word: "Elaborate", pos: "verb", meaning: "To explain in more detail.", example: "Could you elaborate on that point?" },
{ word: "Emerge", pos: "verb", meaning: "To come out or appear.", example: "New trends emerge each year." },
{ word: "Enhance", pos: "verb", meaning: "To improve the quality of something.", example: "Reading enhances your vocabulary." },
{ word: "Environment", pos: "noun", meaning: "The surroundings in which we live.", example: "We must protect the environment." },
{ word: "Equivalent", pos: "adjective", meaning: "Equal in value or meaning.", example: "One kilometre is equivalent to 1000 metres." },
{ word: "Establish", pos: "verb", meaning: "To set up on a firm basis.", example: "They established a new business." },
{ word: "Evaluate", pos: "verb", meaning: "To judge the value of something.", example: "Teachers evaluate student work." },
{ word: "Evidence", pos: "noun", meaning: "Facts that prove something.", example: "There is evidence of climate change." },
{ word: "Exaggerate", pos: "verb", meaning: "To make something seem bigger than it is.", example: "Do not exaggerate your skills." },
{ word: "Excellent", pos: "adjective", meaning: "Extremely good.", example: "She did excellent work this week." },
{ word: "Expand", pos: "verb", meaning: "To make larger.", example: "The company plans to expand overseas." },
{ word: "Expertise", pos: "noun", meaning: "Expert skill or knowledge.", example: "Her expertise is in design." },
{ word: "Explicit", pos: "adjective", meaning: "Stated clearly and in detail.", example: "Give explicit instructions to avoid confusion." },
{ word: "Familiar", pos: "adjective", meaning: "Well known to you.", example: "Her face looks familiar." },
{ word: "Foundation", pos: "noun", meaning: "The basic part on which something is built.", example: "Grammar is the foundation of writing." },
{ word: "Fundamental", pos: "adjective", meaning: "Of central importance.", example: "Reading is a fundamental skill." },
{ word: "Generate", pos: "verb", meaning: "To produce or create.", example: "Solar panels generate electricity." },
{ word: "Genuine", pos: "adjective", meaning: "Truly what it is said to be.", example: "He showed genuine interest in helping." },
{ word: "Guarantee", pos: "verb", meaning: "To promise something will happen.", example: "I cannot guarantee the result." },
{ word: "Hierarchy", pos: "noun", meaning: "A system ranked by status.", example: "There is a clear hierarchy at work." },
{ word: "Hypothesis", pos: "noun", meaning: "A suggested explanation tested by research.", example: "Scientists tested the hypothesis." },
{ word: "Identify", pos: "verb", meaning: "To recognise or name.", example: "Identify the main idea of the text." },
{ word: "Implement", pos: "verb", meaning: "To put a plan into action.", example: "The school implemented new rules." },
{ word: "Indicate", pos: "verb", meaning: "To point out or show.", example: "The data indicates a positive trend." },
{ word: "Influence", pos: "noun", meaning: "The power to affect something.", example: "Parents have a strong influence on children." },
{ word: "Innovative", pos: "adjective", meaning: "Featuring new methods or ideas.", example: "Innovative apps change the way we learn." },
{ word: "Integrate", pos: "verb", meaning: "To combine into a whole.", example: "Migrants try to integrate into society." },
{ word: "Interpret", pos: "verb", meaning: "To explain the meaning of.", example: "She interprets data for the company." },
{ word: "Investigate", pos: "verb", meaning: "To examine carefully.", example: "Police investigate the case." },
{ word: "Justify", pos: "verb", meaning: "To show something is right.", example: "Justify your answer with examples." },
{ word: "Knowledge", pos: "noun", meaning: "Information gained through learning.", example: "Knowledge of grammar is essential." },
{ word: "Legitimate", pos: "adjective", meaning: "Conforming to the law or accepted rules.", example: "He has a legitimate reason to be late." },
{ word: "Manipulate", pos: "verb", meaning: "To control or influence cleverly.", example: "Do not manipulate the results." },
{ word: "Maintain", pos: "verb", meaning: "To keep in good condition.", example: "Maintain your study routine daily." },
{ word: "Mandatory", pos: "adjective", meaning: "Required by law or rules.", example: "Wearing helmets is mandatory." },
{ word: "Mechanism", pos: "noun", meaning: "A system that produces an action.", example: "The mechanism of the clock is complex." },
{ word: "Negotiate", pos: "verb", meaning: "To reach an agreement by discussion.", example: "They negotiated a better salary." },
{ word: "Objective", pos: "noun", meaning: "A goal you want to achieve.", example: "Her objective is to pass the exam." },
{ word: "Obvious", pos: "adjective", meaning: "Easy to see or understand.", example: "It was obvious he was tired." },
{ word: "Occupation", pos: "noun", meaning: "A person's job.", example: "Her occupation is nursing." },
{ word: "Opportunity", pos: "noun", meaning: "A chance for progress.", example: "Studying abroad is a great opportunity." },
{ word: "Participate", pos: "verb", meaning: "To take part in.", example: "Participate in class discussions to learn." },
{ word: "Perspective", pos: "noun", meaning: "A particular point of view.", example: "Try to see things from her perspective." },
{ word: "Phenomenon", pos: "noun", meaning: "An observable fact or event.", example: "Rainbows are a natural phenomenon." },
{ word: "Potential", pos: "noun", meaning: "Latent qualities for development.", example: "She has the potential to be a leader." },
{ word: "Precise", pos: "adjective", meaning: "Exact and accurate.", example: "Give precise measurements." },
{ word: "Predict", pos: "verb", meaning: "To say what will happen in the future.", example: "It is hard to predict the weather." },
{ word: "Preliminary", pos: "adjective", meaning: "Done before the main part.", example: "Preliminary results look good." },
{ word: "Previous", pos: "adjective", meaning: "Existing or occurring before.", example: "In my previous job, I taught English." },
{ word: "Priority", pos: "noun", meaning: "Something more important than others.", example: "Family is my top priority." },
{ word: "Procedure", pos: "noun", meaning: "An established way of doing things.", example: "Follow the safety procedure carefully." },
{ word: "Recognise", pos: "verb", meaning: "To identify someone or something known.", example: "I recognise that song." },
{ word: "Recommend", pos: "verb", meaning: "To suggest as good.", example: "I recommend this book to students." },
{ word: "Reluctant", pos: "adjective", meaning: "Unwilling and hesitant.", example: "He was reluctant to speak in public." },
{ word: "Significant", pos: "adjective", meaning: "Important or large enough to matter.", example: "There was a significant rise in prices." },
{ word: "Strategy", pos: "noun", meaning: "A plan to achieve a goal.", example: "Good strategy helps you score higher." },
{ word: "Sufficient", pos: "adjective", meaning: "Enough for a purpose.", example: "She has sufficient funds to travel." },
{ word: "Thorough", pos: "adjective", meaning: "Complete and careful.", example: "Do a thorough review before the exam." },
{ word: "Tolerate", pos: "verb", meaning: "To accept or endure.", example: "I cannot tolerate rude behaviour." },
{ word: "Transparent", pos: "adjective", meaning: "Open and honest.", example: "The company is transparent about pricing." },
{ word: "Ultimate", pos: "adjective", meaning: "Being the best or final.", example: "Her ultimate goal is permanent residency." },
{ word: "Unique", pos: "adjective", meaning: "Being the only one of its kind.", example: "Every person has a unique fingerprint." },
{ word: "Vague", pos: "adjective", meaning: "Not clearly expressed.", example: "His answer was vague and unhelpful." },
{ word: "Voluntary", pos: "adjective", meaning: "Done willingly without being forced.", example: "She does voluntary work at the shelter." },
];
